package com.mycompany.maven.vista;

import com.mycompany.maven.daoImpl.AlumnoDaoImpl;
import com.mycompany.maven.daoImpl.EscuelaDaoImpl;
import com.mycompany.maven.entity.Alumno;
import com.mycompany.maven.entity.Escuela;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Docente
 */
public class AlumnoFrame extends javax.swing.JFrame {

    private AlumnoDaoImpl alumnDao = new AlumnoDaoImpl();
    private EscuelaDaoImpl escuelaDao = new EscuelaDaoImpl();
    private DefaultTableModel dtm;
    private DefaultComboBoxModel model;
    private int ide = -1;
    private int fila = -1;

    /**
     * Creates new form AlumnoFrame
     */
    public AlumnoFrame() {
        initComponents();
        listarEscuela();
        listarAlumnos();
        desabilitar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboEscuela = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbalumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ALUMNO");

        jLabel2.setText("Escuela:");

        cboEscuela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEscuelaItemStateChanged(evt);
            }
        });
        cboEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEscuelaActionPerformed(evt);
            }
        });
        cboEscuela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboEscuelaKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombres:");

        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombresKeyReleased(evt);
            }
        });

        jLabel4.setText("Apellidos:");

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidosKeyReleased(evt);
            }
        });

        jLabel5.setText("Dirección:");

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
        });

        jLabel6.setText("Correo:");

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(cboEscuela, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombres)
                    .addComponent(jLabel5)
                    .addComponent(txtdireccion))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Listado de Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ALUMNO", "ALUMNO", "DIRECCION", "CORREO", "ESCUELA"
            }
        ));
        tbalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbalumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbalumnos);
        if (tbalumnos.getColumnModel().getColumnCount() > 0) {
            tbalumnos.getColumnModel().getColumn(0).setMinWidth(100);
            tbalumnos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbalumnos.getColumnModel().getColumn(0).setMaxWidth(100);
            tbalumnos.getColumnModel().getColumn(1).setMinWidth(250);
            tbalumnos.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbalumnos.getColumnModel().getColumn(1).setMaxWidth(250);
            tbalumnos.getColumnModel().getColumn(2).setMinWidth(150);
            tbalumnos.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbalumnos.getColumnModel().getColumn(2).setMaxWidth(150);
            tbalumnos.getColumnModel().getColumn(3).setMinWidth(130);
            tbalumnos.getColumnModel().getColumn(3).setPreferredWidth(130);
            tbalumnos.getColumnModel().getColumn(3).setMaxWidth(130);
            tbalumnos.getColumnModel().getColumn(4).setMinWidth(110);
            tbalumnos.getColumnModel().getColumn(4).setPreferredWidth(110);
            tbalumnos.getColumnModel().getColumn(4).setMaxWidth(110);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (alumnDao.create(new Alumno(0, txtnombres.getText(), txtapellidos.getText(), txtdireccion.getText(), txtcorreo.getText(), escuelaDao.read2(cboEscuela.getSelectedItem().toString()).getIdescuela())) == 1) {
            JOptionPane.showMessageDialog(rootPane, "Registro Guardado correctamente....");
            limpiartabla();
            listarAlumnos();
            desabilitar();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pudo guardar el registro");

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cboEscuelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEscuelaItemStateChanged
        // TODO add your handling code here: 
        if (cboEscuela.getSelectedIndex() > 0) {
            txtnombres.setEnabled(true);
            txtnombres.requestFocus();

        }
        /*
        Escuela ee = escuelaDao.read2(cboEscuela.getSelectedItem().toString());
        System.out.println("Id: "+ ee.getIdescuela());*/
    }//GEN-LAST:event_cboEscuelaItemStateChanged

    private void cboEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEscuelaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cboEscuelaActionPerformed

    private void txtnombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyReleased

        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtapellidos.setEnabled(true);
            txtapellidos.requestFocus();
        }

    }//GEN-LAST:event_txtnombresKeyReleased

    private void txtapellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyReleased

        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtdireccion.setEnabled(true);
            txtdireccion.requestFocus();
        }
    }//GEN-LAST:event_txtapellidosKeyReleased

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtcorreo.setEnabled(true);
            txtcorreo.requestFocus();
        }
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        desabilitar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGuardar.setSelected(true);
        }
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void tbalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbalumnosMouseClicked
        // TODO add your handling code here:
        fila = tbalumnos.getSelectedRow();
        System.out.println("Fila: "+fila);
        //Escuela es = escuelaDao.read2(tbalumnos.getValueAt(fila, 4).toString().trim());
        cboEscuela.setSelectedItem(tbalumnos.getValueAt(fila, 4).toString().trim());
        String nom = tbalumnos.getValueAt(fila, 1).toString();
        String[] nombre = nom.split(" ");
        txtnombres.setText(nombre[0]);
        txtapellidos.setText(nombre[1]);
        txtdireccion.setText(tbalumnos.getValueAt(fila, 2).toString());
        txtcorreo.setText(tbalumnos.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tbalumnosMouseClicked

    private void cboEscuelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboEscuelaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cboEscuelaKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (fila >= 0) {
            int resp = JOptionPane.showConfirmDialog(null, "Realmente desea Modificar al Alumno...!");
            if (JOptionPane.OK_OPTION == resp) {
                int ida = Integer.parseInt(tbalumnos.getValueAt(fila, 0).toString());
                Alumno al = new Alumno();
                al.setIdalumno(Integer.parseInt(tbalumnos.getValueAt(fila, 0).toString()));
                al.setNombres(txtnombres.getText());
                al.setApellidos(txtapellidos.getText());
                al.setDireccion(txtdireccion.getText());
                al.setCorreo(txtcorreo.getText());
                al.setIdescuela(escuelaDao.read2(cboEscuela.getSelectedItem().toString()).getIdescuela());
                int op = alumnDao.update(al);
                if (op == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Registro Modificado correctamente...!");
                    limpiartabla();
                    desabilitar();
                    listarAlumnos();
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo Modificado el Alumno...!");
                }
            } else {
                System.out.println("No selecciona una opción afirmativa");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccionar Alumno...!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (fila >= 0) {
            int resp = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar al Alumno...!");
            if (JOptionPane.OK_OPTION == resp) {
                System.out.println("Selecciona opción Afirmativa");
                int ida = Integer.parseInt(tbalumnos.getValueAt(fila, 0).toString());
                int op = alumnDao.delete(ida);
                if (op == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Registro Eliminado correctamente...!");
                    limpiartabla();
                    desabilitar();
                    listarAlumnos();
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo Eliminar el Alumno...!");
                }
            } else {
                System.out.println("No selecciona una opción afirmativa");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccionar Alumno...!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void listarEscuela() {
        model = (DefaultComboBoxModel) cboEscuela.getModel();
        List<Escuela> lista = escuelaDao.readAll();
        cboEscuela.addItem("Seleccionar Escuela...");
        for (int i = 0; i < lista.size(); i++) {
            model.addElement(lista.get(i).getNombre());
        }
        cboEscuela.setModel(model);
    }

    public void listarAlumnos() {
        dtm = (DefaultTableModel) tbalumnos.getModel();
        List<Map<String, Object>> lista1 = alumnDao.lista();
        Object[] datos = new Object[5];
        lista1.forEach(map -> {
            datos[0] = map.get("idalumno");
            datos[1] = map.get("nombres") + " " + map.get("apellidos");
            datos[2] = map.get("direccion");
            datos[3] = map.get("correo");
            datos[4] = map.get("escuela");
            dtm.addRow(datos);
        });
        tbalumnos.setModel(dtm);
    }

    public void desabilitar() {
        cboEscuela.setSelectedIndex(0);
        txtnombres.setText(null);
        txtapellidos.setText(null);
        txtdireccion.setText(null);
        txtcorreo.setText(null);
        txtnombres.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtcorreo.setEnabled(false);
    }

    public void limpiartabla() {
        for (int i = 0; i < tbalumnos.getRowCount(); i++) {
            dtm.removeRow(i);
            i -= 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEscuela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbalumnos;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
